function z = f(x,y)

% z = -4;

%%%%%% Exam Project

% Equation 1
%z = -2*x^2 ...
%	 + 3*x*(2*x - (sin(x))^2 + (cos(x))^2) ...
% 	 + 4*y^2 ...
%    - (-4*sin(x)*cos(x) + 2)*(x^2+y^2+1) ...
%    + (x^2 + y^2 + sin(x)*cos(x))*exp(x*y) ...
%    -2;

% Equation 2
z = 3*x*(x*cos(y) + exp(x+y) + sin(x)) ...
    - 3*y*(y*cos(x) + exp(x+y) + sin(y)) ...
    - (3*x*y + 14)*(-x*sin(y) + exp(x+y)) ...
    - (3*x*y + 14)*(-y*sin(x) + exp(x+y)) ...
    + (x*sin(y) + y*sin(x) + exp(x+y))*(x^2 + y^2 + 5);
 
end
